version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./pong-server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  # client:
  #   container_name: client
  #   build: ./frontend/
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - server

  server:
    container_name: server
    build: ./pong-server/
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - public:/usr/src/app/public

volumes:
  pgdata:
  public: